apiVersion: apps/v1
kind: Deployment
metadata:
  name: browser
spec:
  replicas: 3
  selector:
    matchLabels:
      app: browser
  template:
    metadata:
      labels:
        app: browser
    spec:
      containers:
      - image: ghcr.io/buildbarn/bb-browser:20231103T134227Z-794e380
        args:
        - /config/browser.jsonnet
        name: browser
        ports:
        - containerPort: 7984
          protocol: TCP
        volumeMounts:
        - mountPath: /config/
          name: configs
          readOnly: true
      volumes:
      - name: configs
        projected:
          sources:
          - configMap:
              name: browser
              items:
              - key: browser.jsonnet
                path: browser.jsonnet
          - configMap:
              name: common
              items:
              - key: common.libsonnet
                path: common.libsonnet
---
apiVersion: v1
kind: Service
metadata:
  name: browser
  annotations:
    prometheus.io/port: "80"
    prometheus.io/scrape: "true"
spec:
  ports:
  - port: 7984
    protocol: TCP
    name: http
  selector:
    app: browser
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: browser
spec:
  ingressClassName: nginx
  rules:
  - host: {{ required "Missing .browser.host value" .Values.browser.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: browser
            port:
              name: http
