---
environments:
  dev:
    kubeContext: buildbarn-cluster

---
repositories:
- name: prometheus
  url: https://prometheus-community.github.io/helm-charts
- name: cluster-autoscaler
  url: https://kubernetes.github.io/autoscaler
- name: aws
  url: https://aws.github.io/eks-charts
- name: metrics-server
  url: https://kubernetes-sigs.github.io/metrics-server
- name: grafana
  url: https://grafana.github.io/helm-charts
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx

helmDefaults:
  verify: false
  wait: true
  waitForJobs: true
  timeout: 600
  recreatePods: false
  force: false
  historyMax: 10
  createNamespace: true

releases:
  - name: cluster-autoscaler
    namespace: kube-system
    chart: cluster-autoscaler/cluster-autoscaler
    version: 9.34.0
    values:
      - manifests/cluster-autoscaler.yaml
      - local/cluster-autoscaler.yaml

  - name: metrics-server
    namespace: kube-system
    chart: metrics-server/metrics-server
    version: 3.11.0
    values: []

  - name: external-dns
    namespace: kube-system
    chart: bitnami/external-dns
    version: 6.28.6
    values:
      - manifests/external-dns.yaml
      - local/external-dns.yaml

  - name: storage-class
    namespace: kube-system
    chart: charts/storage-class
    version: 1.0.0

  - name: ingress-nginx
    namespace: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    version: 4.8.4
    values:
      - manifests/ingress-nginx.yaml
      - local/ingress-nginx.yaml

  - name: buildbarn
    namespace: buildbarn
    chart: charts/buildbarn
    version: 1.0.0
    {{/* needs: */}}
    {{/*   - ingress-nginx */}}
    {{/*   - external-dns */}}
    {{/*   - storage-class */}}
    values:
      - local/buildbarn.yaml
